YUTPLAT/Models/Medicion.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using static YUTPLAT.Enums.Enum;

namespace YUTPLAT.Models
{
    public class Medicion
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int MedicionId { get; set; }

        public virtual Indicador Indicador { get; set; }
        public int IndicadorID { get; set; }
        public int Anio { get; set; }
        public Mes Mes { get; set; }
        public decimal Valor { get; set; }        
        public DateTime? FechaCarga { get; set; }
        public string UsuarioCargo { get; set; }        
        public string Comentario { get; set; }
        public bool SeDebeNotificar { get; set; }
        public bool NoAplica { get; set; }
    }
}

YUTPLAT/Controllers/MedicionController.cs
using System.Web.Mvc;
using YUTPLAT.Services.Interface;
using System.Threading.Tasks;
using YUTPLAT.Helpers;
using System;
using YUTPLAT.Helpers.Filters;

namespace YUTPLAT.Controllers
{
    [Authorize]
    public class MedicionController : Controller
    {
        public IMedicionService MedicionService { get; set; }
        public IIndicadorAutomaticoService IndicadorAutomaticoService { get; set; }
        public IAnioTableroService AnioTableroService { get; set; }

        public MedicionController(IMedicionService medicionService,
                                  IIndicadorAutomaticoService indicadorAutomaticoService,
                                  AnioTableroService anioTableroService)
        {
            this.MedicionService = medicionService;
            IndicadorAutomaticoService = indicadorAutomaticoService;
            AnioTableroService = anioTableroService;
        }

        public async Task<JsonResult> Recalcular(int idIndicador, int mes)
        {
            int anio = (await AnioTableroService.GetById(Int32.Parse((string)Session["IdAnioTablero"]))).Anio;
                        
            decimal valor = IndicadorAutomaticoService.RecalcularIndicador(anio, mes, idIndicador);
            return Json(valor, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [EncryptedActionParameter]
        public async Task<FileContentResult> ExportToExcel(string mes, string idIndicador)
        {
            int anio = (await AnioTableroService.GetById(Int32.Parse((string)Session["IdAnioTablero"]))).Anio;
            return File(IndicadorAutomaticoService.ObtenerArchivo(anio, Int32.Parse(mes), Int32.Parse(idIndicador)), ExcelExportHelper.ExcelContentType, "DetalleIndicador.xlsx");
        }
    }    
}

YUTPLAT/Views/Shared/Medicion/_Crear.cshtml
@using YUTPLAT.ViewModel
@model MedicionViewModel

<script type="text/javascript">
    jQuery(document).ready(function () {

        jQuery(".errorGeneral").hide();

        jQuery("input[type=text]").keydown(function () {
            jQuery(".errorGeneral").hide();
        });

        jQuery('#form').submit(function () {

            jQuery(".errorGeneralSummary").hide();

            if (!jQuery('#form').valid()) {
                jQuery(".errorGeneral").show();
                return false;
            }
            else {
                jQuery.ajax({
                    url: this.action,
                    type: this.method,

                    data: jQuery(this).serialize(),
                    success: function (result) {
                        if (result.success) {
                            jQuery('#cargaMedicionModal').modal('hide');
                            var serviceURL = '@Url.Action("Ver", "Tablero", new { q = YUTPLAT.Helpers.MyExtensions.Encrypt(new { msgExito = "La medición se ha guardado exitosamente." }) })';
                            window.location.href = serviceURL;
                        } else {
                            jQuery('#contenidoModal').html(result);
                        }
                    }
                });

                return false;

            }
        });

        jQuery("#Valor").keydown(function (e) {
            // Allow: backspace, delete, tab, escape, enter and .
            if (jQuery.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190, 109]) !== -1 ||
                // Allow: Ctrl+A, Command+A
                (e.keyCode === 65 && (e.ctrlKey === true || e.metaKey === true)) ||
                // Allow: home, end, left, right, down, up
                (e.keyCode >= 35 && e.keyCode <= 40)) {
                // let it happen, don't do anything
                return;
            }
            // Ensure that it is a number and stop the keypress
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                e.preventDefault();
            }
        });

        jQuery("#NoAplica").click(function () {
            jQuery("#Valor").val("");

            var noAplica = jQuery('#NoAplica').prop('checked');
            jQuery("#Valor").prop('disabled', noAplica);

            if (noAplica) {
                jQuery("#Valor").rules("remove", "required");
            }            
        });
        
        if (jQuery('#NoAplica').prop('checked')) {
            jQuery("#Valor").val("");
        }

        jQuery("#Valor").prop('disabled', jQuery('#NoAplica').prop('checked'));

    });

    function cerrar() {
        jQuery.ajax({
            url: '@Url.Action("CerrarPopup", "Tablero")',
            type: 'post',
            beforeSend: function () {
            },
            success: function (response) {
            },
            complete: function (data) {
            }
        });
    }
</script>

@using (Html.BeginForm("CargarMedicion", "Tablero", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { id = "form", role = "form" }))
{
    <div class="modal-body">

        @Html.ValidationSummary(true, "", new { @class = "text-danger errorGeneralSummary" })

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="row">
                    <div class="col-xs-6 col-sm-3 col-md-3">
                        @Html.LabelFor(m => m.Valor)
                        @Html.TextBoxFor(m => m.Valor, new { @class = "form-control" })

                    </div>
                    <div class="col-xs-3 col-sm-3 col-md-3">
                        <div class="form-check">
                            <label>
                                @Html.CheckBoxFor(m => m.NoAplica) <span class="label-text">No aplica</span>
                            </label>
                        </div>
                    </div>
                </div>
                <span class="aclaracion">(caracter punto "." como separador decimal)</span>
                @Html.ValidationMessageFor(m => m.Valor, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                @Html.LabelFor(m => m.Comentario)
                @Html.TextAreaFor(m => m.Comentario, new { @rows = 2, @class = "form-control" })
                <span class="aclaracion">(máximo 2000 caracteres)</span>
                @Html.ValidationMessageFor(m => m.Comentario, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6">
                @Html.LabelFor(m => m.IndicadorViewModel.Descripcion)
                <span class="aclaracion">@Model.IndicadorViewModel.Descripcion </span>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                @Html.LabelFor(m => m.IndicadorViewModel.ObjetivoID)
                <span class="aclaracion">@Model.IndicadorViewModel.ObjetivoViewModel.Descripcion </span>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-6 col-sm-2 col-md-2">
                @Html.LabelFor(m => m.IndicadorViewModel.MetaExcelenteViewModel)
                <span class="aclaracion">@Model.IndicadorViewModel.MetaExcelenteViewModel.ToString()</span>
            </div>
            <div class="col-xs-6 col-sm-2 col-md-2">
                @Html.LabelFor(m => m.IndicadorViewModel.MetaSatisfactoriaViewModel)
                <span class="aclaracion">@Model.IndicadorViewModel.MetaSatisfactoriaViewModel.ToString()</span>
            </div>
            <div class="col-xs-6 col-sm-2 col-md-2">
                @Html.LabelFor(m => m.IndicadorViewModel.MetaAceptableViewModel)
                <span class="aclaracion">@Model.IndicadorViewModel.MetaAceptableViewModel.ToString()</span>
            </div>
            <div class="col-xs-6 col-sm-2 col-md-2">
                @Html.LabelFor(m => m.IndicadorViewModel.MetaAMejorarViewModel)
                <span class="aclaracion">@Model.IndicadorViewModel.MetaAMejorarViewModel.ToString()</span>
            </div>
            <div class="col-xs-6 col-sm-2 col-md-2">
                @Html.LabelFor(m => m.IndicadorViewModel.MetaInaceptableViewModel)
                <span class="aclaracion">@Model.IndicadorViewModel.MetaInaceptableViewModel.ToString()</span>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <input type="submit" class="btn btn-fill btn-info" value="Guardar" />
        <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="javascript:cerrar();">Cerrar</button>
    </div>

    @Html.HiddenFor(m => m.IndicadorID)
    @Html.HiddenFor(m => m.MedicionId)
    @Html.HiddenFor(m => m.Mes)

    @Html.HiddenFor(m => m.IndicadorViewModel.Nombre)

    @Html.HiddenFor(m => m.IndicadorViewModel.MetaExcelenteViewModel.Signo1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaExcelenteViewModel.Signo2)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaExcelenteViewModel.Valor1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaExcelenteViewModel.Valor2)

    @Html.HiddenFor(m => m.IndicadorViewModel.MetaSatisfactoriaViewModel.Signo1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaSatisfactoriaViewModel.Signo2)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaSatisfactoriaViewModel.Valor1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaSatisfactoriaViewModel.Valor2)

    @Html.HiddenFor(m => m.IndicadorViewModel.MetaAceptableViewModel.Signo1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaAceptableViewModel.Signo2)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaAceptableViewModel.Valor1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaAceptableViewModel.Valor2)

    @Html.HiddenFor(m => m.IndicadorViewModel.MetaAMejorarViewModel.Signo1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaAMejorarViewModel.Signo2)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaAMejorarViewModel.Valor1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaAMejorarViewModel.Valor2)

    @Html.HiddenFor(m => m.IndicadorViewModel.MetaInaceptableViewModel.Signo1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaInaceptableViewModel.Signo2)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaInaceptableViewModel.Valor1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaInaceptableViewModel.Valor2)
}

YUTPLAT/Views/Shared/Medicion/_CrearAutomatico.cshtml
@using YUTPLAT.ViewModel
@using YUTPLAT.Helpers

@model MedicionViewModel

<script type="text/javascript">
    jQuery(document).ready(function () {

        jQuery(".errorGeneral").hide();

        jQuery("input[type=text]").keydown(function () {
            jQuery(".errorGeneral").hide();
        });

        jQuery('#form').submit(function () {

            jQuery(".errorGeneralSummary").hide();

            if (!jQuery('#form').valid()) {
                jQuery(".errorGeneral").show();
                return false;
            }
            else {
                jQuery.ajax({
                    url: this.action,
                    type: this.method,

                    data: jQuery(this).serialize(),
                    success: function (result) {
                        if (result.success) {
                            jQuery('#cargaMedicionModal').modal('hide');
                            var serviceURL = '@Url.Action("Ver", "Tablero", new { q = YUTPLAT.Helpers.MyExtensions.Encrypt(new { msgExito = "La medición se ha guardado exitosamente." }) })';
                            window.location.href = serviceURL;
                        } else {
                            jQuery('#contenidoModal').html(result);
                        }
                    }
                });

                return false;

            }
        });

        jQuery("#Valor").keydown(function (e) {
            // Allow: backspace, delete, tab, escape, enter and .
            if (jQuery.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190, 109]) !== -1 ||
                // Allow: Ctrl+A, Command+A
                (e.keyCode === 65 && (e.ctrlKey === true || e.metaKey === true)) ||
                // Allow: home, end, left, right, down, up
                (e.keyCode >= 35 && e.keyCode <= 40)) {
                // let it happen, don't do anything
                return;
            }
            // Ensure that it is a number and stop the keypress
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                e.preventDefault();
            }
        });
    });

    function recalcularMedicion() {
        var parametros = {
            "idIndicador": jQuery("#IndicadorViewModel_Id").val(),
            "mes": jQuery("#Mes").val()
        };
        jQuery.ajax({
            data: parametros,
            url: '@Url.Action("Recalcular", "Medicion")',
            type: 'post',
            beforeSend: function () {
                jQuery("#loader").show();
            },
            success: function (response) {
                jQuery("#Valor").val(response);
            },
            complete: function (data) {
                jQuery("#loader").hide();
            }
        });
    }

    function cerrar() {       
        jQuery.ajax({            
            url: '@Url.Action("CerrarPopup", "Tablero")',
            type: 'post',
            beforeSend: function () {                
            },
            success: function (response) {               
            },
            complete: function (data) {               
            }
        });
    }

</script>

@using (Html.BeginForm("CargarMedicionAutomatica", "Tablero", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { id = "form", role = "form" }))
{
    <div class="modal-body">
        @Html.ValidationSummary(true, "", new { @class = "text-danger errorGeneralSummary" })
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                @Html.LabelFor(m => m.Valor)
                <div class="row">
                    <div class="col-xs-3 col-sm-3 col-md-3">
                        @Html.TextBoxFor(m => m.Valor, new { @class = "form-control" })
                    </div>
                    <div class="col-xs-4 col-sm-2 col-md-2">
                        <button type="button" class="btn btn-secondary" onclick="javascript:recalcularMedicion();">Recalcular</button>
                    </div>
                    <div class="col-xs-4 col-sm-2 col-md-2">
                        <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("ExportToExcel", "Medicion", new { q = MyExtensions.Encrypt(new { mes = (int)Model.Mes, idIndicador = Model.IndicadorID }) })'">Exportar</button>
                    </div>
                    <div class="col-xs-1 col-sm-1 col-md-1">
                        <div id="loader" style="display: none;">
                            <img src="~/images/loading.gif" width="32px" height="32px">
                        </div>
                    </div>
                </div>
                <span class="aclaracion">(caracter punto "." como separador decimal)</span>
                @Html.ValidationMessageFor(m => m.Valor, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-12 col-sm-12 col-md-12">
                @Html.LabelFor(m => m.Comentario)
                @Html.TextAreaFor(m => m.Comentario, new { @rows = 2, @class = "form-control" })
                <span class="aclaracion">(máximo 2000 caracteres)</span>
                @Html.ValidationMessageFor(m => m.Comentario, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6">
                @Html.LabelFor(m => m.IndicadorViewModel.Descripcion)
                <span class="aclaracion">@Model.IndicadorViewModel.Descripcion </span>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                @Html.LabelFor(m => m.IndicadorViewModel.ObjetivoID)
                <span class="aclaracion">@Model.IndicadorViewModel.ObjetivoViewModel.Descripcion </span>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-6 col-sm-2 col-md-2">
                @Html.LabelFor(m => m.IndicadorViewModel.MetaExcelenteViewModel)
                <span class="aclaracion">@Model.IndicadorViewModel.MetaExcelenteViewModel.ToString()</span>
            </div>
            <div class="col-xs-6 col-sm-2 col-md-2">
                @Html.LabelFor(m => m.IndicadorViewModel.MetaSatisfactoriaViewModel)
                <span class="aclaracion">@Model.IndicadorViewModel.MetaSatisfactoriaViewModel.ToString()</span>
            </div>
            <div class="col-xs-6 col-sm-2 col-md-2">
                @Html.LabelFor(m => m.IndicadorViewModel.MetaAceptableViewModel)
                <span class="aclaracion">@Model.IndicadorViewModel.MetaAceptableViewModel.ToString()</span>
            </div>
            <div class="col-xs-6 col-sm-2 col-md-2">
                @Html.LabelFor(m => m.IndicadorViewModel.MetaAMejorarViewModel)
                <span class="aclaracion">@Model.IndicadorViewModel.MetaAMejorarViewModel.ToString()</span>
            </div>
            <div class="col-xs-6 col-sm-2 col-md-2">
                @Html.LabelFor(m => m.IndicadorViewModel.MetaInaceptableViewModel)
                <span class="aclaracion">@Model.IndicadorViewModel.MetaInaceptableViewModel.ToString()</span>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <input type="submit" class="btn btn-fill btn-info" value="Guardar" />
        <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="javascript:cerrar();">Cerrar</button>
    </div>

    @Html.HiddenFor(m => m.IndicadorID)
    @Html.HiddenFor(m => m.MedicionId)
    @Html.HiddenFor(m => m.Mes)

    @Html.HiddenFor(m => m.IndicadorViewModel.Id)
    @Html.HiddenFor(m => m.IndicadorViewModel.Nombre)

    @Html.HiddenFor(m => m.IndicadorViewModel.MetaExcelenteViewModel.Signo1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaExcelenteViewModel.Signo2)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaExcelenteViewModel.Valor1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaExcelenteViewModel.Valor2)

    @Html.HiddenFor(m => m.IndicadorViewModel.MetaSatisfactoriaViewModel.Signo1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaSatisfactoriaViewModel.Signo2)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaSatisfactoriaViewModel.Valor1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaSatisfactoriaViewModel.Valor2)

    @Html.HiddenFor(m => m.IndicadorViewModel.MetaAceptableViewModel.Signo1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaAceptableViewModel.Signo2)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaAceptableViewModel.Valor1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaAceptableViewModel.Valor2)

    @Html.HiddenFor(m => m.IndicadorViewModel.MetaAMejorarViewModel.Signo1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaAMejorarViewModel.Signo2)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaAMejorarViewModel.Valor1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaAMejorarViewModel.Valor2)

    @Html.HiddenFor(m => m.IndicadorViewModel.MetaInaceptableViewModel.Signo1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaInaceptableViewModel.Signo2)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaInaceptableViewModel.Valor1)
    @Html.HiddenFor(m => m.IndicadorViewModel.MetaInaceptableViewModel.Valor2)
}

YUTPLAT/Views/Shared/Medicion/_Ver.cshtml
@using YUTPLAT.ViewModel
@using YUTPLAT.Helpers

@model MedicionViewModel

<script type="text/javascript">
    function cerrar() {
        jQuery.ajax({
            url: '@Url.Action("CerrarPopup", "Tablero")',
            type: 'post',
            beforeSend: function () {
            },
            success: function (response) {
            },
            complete: function (data) {
            }
        });
    }

</script>

<div class="modal-body">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            @Html.LabelFor(m => m.Valor)
            <div class="row">
                <div class="col-xs-6 col-sm-3 col-md-3">
                    @Html.TextBoxFor(m => m.Valor, new { @disabled = "true", @class = "form-control" })
                </div>
                @if (Model.EsIndicadorAutomatico)
                {
                    <div class="col-xs-4 col-sm-2 col-md-2">
                        <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("ExportToExcel", "Medicion", new { q = MyExtensions.Encrypt(new { mes = (int)Model.Mes, idIndicador = Model.IndicadorID }) })'">Exportar</button>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            @Html.LabelFor(m => m.Comentario)
            @Html.TextAreaFor(m => m.Comentario, new { @disabled = "true", @rows = 3, @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
            @Html.LabelFor(m => m.IndicadorViewModel.Descripcion)
            <span class="aclaracion">@Model.IndicadorViewModel.Descripcion </span>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6">
            @Html.LabelFor(m => m.IndicadorViewModel.ObjetivoID)
            <span class="aclaracion">@Model.IndicadorViewModel.ObjetivoViewModel.Descripcion </span>
        </div>
    </div>
    <div class="row">
        <br />
        <div class="col-xs-6 col-sm-2 col-md-2">
            @Html.LabelFor(m => m.IndicadorViewModel.MetaExcelenteViewModel)
            <span class="aclaracion">@Model.IndicadorViewModel.MetaExcelenteViewModel.ToString()</span>
        </div>
        <div class="col-xs-6 col-sm-2 col-md-2">
            @Html.LabelFor(m => m.IndicadorViewModel.MetaSatisfactoriaViewModel)
            <span class="aclaracion">@Model.IndicadorViewModel.MetaSatisfactoriaViewModel.ToString()</span>
        </div>
        <div class="col-xs-6 col-sm-2 col-md-2">
            @Html.LabelFor(m => m.IndicadorViewModel.MetaAceptableViewModel)
            <span class="aclaracion">@Model.IndicadorViewModel.MetaAceptableViewModel.ToString()</span>
        </div>
        <div class="col-xs-6 col-sm-2 col-md-2">
            @Html.LabelFor(m => m.IndicadorViewModel.MetaAMejorarViewModel)
            <span class="aclaracion">@Model.IndicadorViewModel.MetaAMejorarViewModel.ToString()</span>
        </div>
        <div class="col-xs-6 col-sm-2 col-md-2">
            @Html.LabelFor(m => m.IndicadorViewModel.MetaInaceptableViewModel)
            <span class="aclaracion">@Model.IndicadorViewModel.MetaInaceptableViewModel.ToString()</span>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="javascript:cerrar();">Cerrar</button>
</div>